version: '3.2'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@domain.com'
      PGADMIN_DEFAULT_PASSWORD: 'SuperSecret'
    ports:
      - 8082:80
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      TZ: 'Asia/Tokyo'
      PGTZ: 'Asia/Tokyo'
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass bot
  app:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/opt/app
    ports:
      - 4000:4000
      - 3000:3000
    depends_on:
      - db
    command: iex -S mix phx.server
    environment:
      NODE_ENV: 'development'
      POSTGRES_DB: 'app_dev'
      POSTGRES_HOST: db
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      TZ: 'Asia/Tokyo'
